/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AutoCompleteTextbox {
    /**
    * The filterd data as per searched query
    */
    'data': string[];
    /**
    * This method can be used to change/initialize autocomplete suggestions list. Note - This will not append but reinitialize the suggestion data, so previous suggestion data will be overwritten.
    */
    'initializeData': (d: string[]) => Promise<void>;
    /**
    * This property can be used by host element to make functionality disabled
    */
    'isDisabled': boolean;
  }
}

declare global {


  interface HTMLAutoCompleteTextboxElement extends Components.AutoCompleteTextbox, HTMLStencilElement {}
  var HTMLAutoCompleteTextboxElement: {
    prototype: HTMLAutoCompleteTextboxElement;
    new (): HTMLAutoCompleteTextboxElement;
  };
  interface HTMLElementTagNameMap {
    'auto-complete-textbox': HTMLAutoCompleteTextboxElement;
  }
}

declare namespace LocalJSX {
  interface AutoCompleteTextbox extends JSXBase.HTMLAttributes<HTMLAutoCompleteTextboxElement> {
    /**
    * The filterd data as per searched query
    */
    'data'?: string[];
    /**
    * This property can be used by host element to make functionality disabled
    */
    'isDisabled'?: boolean;
  }

  interface IntrinsicElements {
    'auto-complete-textbox': AutoCompleteTextbox;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


